// clang-format off
{ { { { "***     " } }, 0x1 }, "" },
{ { { { "CONCURRE" } }, 0x2 }, "cbexit" },
{ { { { "CONCURRE" } }, 0x3 }, "SstartP" },
{ { { { "CONCURRE" } }, 0x4 }, "SstopP" },
{ { { { "CONCURRE" } }, 0x6 }, "SExitProcess" },
{ { { { "CUPOPS  " } }, 0x12 }, "TamperingDetected" },
{ { { { "DONESOFA" } }, 0x2 }, "DoStartup" },
{ { { { "DONESOFA" } }, 0x3 }, "DoInter" },
{ { { { "EXTRAHEA" } }, 0x2 }, "s_dispose" },
{ { { { "EXTRAHEA" } }, 0x3 }, "s_var_new" },
{ { { { "EXTRAHEA" } }, 0x4 }, "s_mem_lock" },
{ { { { "EXTRAHEA" } }, 0x5 }, "s_mem_avail:integer" },
{ { { { "EXTRAHEA" } }, 0x6 }, "s_var_avail" },
{ { { { "EXTRAHEA" } }, 0x7 }, "s_mem_swap" },
{ { { { "EXTRAHEA" } }, 0x8 }, "j_dispose" },
{ { { { "EXTRAHEA" } }, 0x9 }, "getname" },
{ { { { "EXTRAIO " } }, 0x2 }, "fblockio" },
{ { { { "EXTRAIO " } }, 0x3 }, "f_writechar" },
{ { { { "FILEOPS " } }, 0x2 }, "open" },
{ { { { "FILEOPS " } }, 0x3 }, "close" },
{ { { { "FILEOPS " } }, 0x4 }, "finit" },
{ { { { "FILEOPS " } }, 0x5 }, "seek" },
{ { { { "FILEOPS " } }, 0x6 }, "reset" },
{ { { { "GEMBIND " } }, 0x2 }, "VDI" },
{ { { { "GEMBIND " } }, 0x3 }, "AES" },
{ { { { "GEMBIND " } }, 0x4 }, "MemoryCopy" },
{ { { { "GEMBIND " } }, 0x5 }, "GetAbsoluteAddress" },
{ { { { "GEMBIND " } }, 0x6 }, "SetScreen" },
{ { { { "GEMBIND " } }, 0x7 }, "DecompressImage" },
{ { { { "GEMBIND " } }, 0x8 }, "DoSound" },
{ { { { "GEMBIND " } }, 0x9 }, "Native09" },
{ { { { "GEMBIND " } }, 0xa }, "FlopFmt" },
{ { { { "GEMBIND " } }, 0xb }, "SetColor" },
{ { { { "GEMBIND " } }, 0xc }, "Native0C" },
{ { { { "GEMBIND " } }, 0xd }, "ScrollScreen" },
{ { { { "GEMBIND " } }, 0xe }, "SetMouseShape" },
{ { { { "GEMBIND " } }, 0xf }, "SetClippingRectangle1" },
{ { { { "GEMBIND " } }, 0x10 }, "PolyLine" },
{ { { { "GEMBIND " } }, 0x11 }, "DrawLine" },
{ { { { "GEMBIND " } }, 0x12 }, "MultiDrawChar" },
{ { { { "GEMBIND " } }, 0x13 }, "DrawChar" },
{ { { { "GEMBIND " } }, 0x14 }, "DrawFilledRectangle" },
{ { { { "GEMBIND " } }, 0x15 }, "DrawEllArc" },
{ { { { "GEMBIND " } }, 0x16 }, "SetWriteMode" },
{ { { { "GEMBIND " } }, 0x17 }, "SetLineWidth" },
{ { { { "GEMBIND " } }, 0x18 }, "SetLineColor" },
{ { { { "GEMBIND " } }, 0x19 }, "SetTextColor" },
{ { { { "GEMBIND " } }, 0x1a }, "SetFillColor" },
{ { { { "GEMBIND " } }, 0x1c }, "DrawColor" },
{ { { { "GEMBIND " } }, 0x1d }, "DrawBW" },
{ { { { "GEMBIND " } }, 0x1e }, "GetMousePosition" },
{ { { { "GEMBIND " } }, 0x1f }, "GetMouseButton" },
{ { { { "GEMBIND " } }, 0x20 }, "DrawIcon" },
{ { { { "GEMBIND " } }, 0x21 }, "DrawBWWriteMode" },
{ { { { "GEMBIND " } }, 0x22 }, "DrawBW?" },
{ { { { "GEMBIND " } }, 0x23 }, "SetClippingRectangle2" },
{ { { { "GEMBIND " } }, 0x26 }, "ShowMouseCursor" },
{ { { { "GEMBIND " } }, 0x27 }, "HideMouseCursor" },
{ { { { "GEMBIND " } }, 0x28 }, "CollisionDetect" },
{ { { { "GEMBIND " } }, 0x29 }, "DrawSprite" },
{ { { { "GEMBIND " } }, 0x2a }, "SpriteMovementEnable" },
{ { { { "GEMBIND " } }, 0x2b }, "SetSprite" },
{ { { { "GEMBIND " } }, 0x2c }, "InstallVBlankHandler" },
{ { { { "GETCMD  " } }, 0x12 }, "PrintPadded" },
{ { { { "GETCMD  " } }, 0x14 }, "PrintSystemInfo" },
{ { { { "GOTOXY  " } }, 0x2 }, "gotoxy" },
{ { { { "GRNDLIB " } }, 0x2 }, "DoCombat" },
{ { { { "GRNDLIB " } }, 0x3 }, "DoMoveOnGround" },
{ { { { "GRNDLIB " } }, 0x4 }, "DoUniteller" },
{ { { { "GRNDLIB " } }, 0x5 }, "DoTrading" },
{ { { { "GRNDLIB " } }, 0x6 }, "DoMoveInBuilding" },
{ { { { "GRNDLIB " } }, 0x7 }, "DoSlots" },
{ { { { "HEAPOPS " } }, 0x2 }, "H_Mark" },
{ { { { "HEAPOPS " } }, 0x3 }, "H_Release" },
{ { { { "HEAPOPS " } }, 0x4 }, "H_New" },
{ { { { "HEAPOPS " } }, 0x5 }, "H_Dispose" },
{ { { { "KERNEL  " } }, 0x2 }, "Exec_Error" },
{ { { { "KERNEL  " } }, 0x4 }, "relocseg" },
{ { { { "KERNEL  " } }, 0x5 }, "ptr_idx" },
{ { { { "KERNEL  " } }, 0x6 }, "ptr_sub" },
{ { { { "KERNEL  " } }, 0x7 }, "UL" },
{ { { { "KERNEL  " } }, 0x8 }, "UG" },
{ { { { "KERNEL  " } }, 0x9 }, "UGE" },
{ { { { "KERNEL  " } }, 0xa }, "PrintLnConsole" },
{ { { { "KERNEL  " } }, 0xb }, "PrintIntConsole" },
{ { { { "KERNEL  " } }, 0xc }, "PrintConsole" },
{ { { { "KERNEL  " } }, 0xe }, "moveseg" },
{ { { { "KERNEL  " } }, 0xf }, "moveleft" },
{ { { { "KERNEL  " } }, 0x10 }, "moveright" },
{ { { { "KERNEL  " } }, 0x11 }, "_exitproc" },
{ { { { "KERNEL  " } }, 0x12 }, "unitread" },
{ { { { "KERNEL  " } }, 0x13 }, "unitwrite" },
{ { { { "KERNEL  " } }, 0x14 }, "time" },
{ { { { "KERNEL  " } }, 0x15 }, "fillchar" },
{ { { { "KERNEL  " } }, 0x16 }, "scan" },
{ { { { "KERNEL  " } }, 0x17 }, "iocheck" },
{ { { { "KERNEL  " } }, 0x18 }, "getpoolbytes" },
{ { { { "KERNEL  " } }, 0x19 }, "putpoolbytes" },
{ { { { "KERNEL  " } }, 0x1a }, "flipsegbytes" },
{ { { { "KERNEL  " } }, 0x1b }, "quiet" },
{ { { { "KERNEL  " } }, 0x1c }, "enable" },
{ { { { "KERNEL  " } }, 0x1d }, "attach" },
{ { { { "KERNEL  " } }, 0x1e }, "ioresult" },
{ { { { "KERNEL  " } }, 0x1f }, "unitbusy" },
{ { { { "KERNEL  " } }, 0x20 }, "poweroften" },
{ { { { "KERNEL  " } }, 0x21 }, "unitwait" },
{ { { { "KERNEL  " } }, 0x22 }, "unitclear" },
{ { { { "KERNEL  " } }, 0x23 }, "_halt" },
{ { { { "KERNEL  " } }, 0x24 }, "unitstatus" },
{ { { { "KERNEL  " } }, 0x25 }, "idsearch" },
{ { { { "KERNEL  " } }, 0x26 }, "treesearch" },
{ { { { "KERNEL  " } }, 0x27 }, "readseg" },
{ { { { "KERNEL  " } }, 0x28 }, "_unitread" },
{ { { { "KERNEL  " } }, 0x29 }, "_unitwrite" },
{ { { { "KERNEL  " } }, 0x2a }, "_unitbusy" },
{ { { { "KERNEL  " } }, 0x2b }, "_unitwait" },
{ { { { "KERNEL  " } }, 0x2c }, "_unitclear" },
{ { { { "KERNEL  " } }, 0x2d }, "_unitstatus" },
{ { { { "KERNEL  " } }, 0x2e }, "_readseg" },
{ { { { "KERNEL  " } }, 0x2f }, "_setrestricted" },
{ { { { "KERNEL  " } }, 0x30 }, "Fault_Handler" },
{ { { { "KERNEL  " } }, 0x36 }, "Swap_Endian" },
{ { { { "KERNEL  " } }, 0x37 }, "Halt" },
{ { { { "KERNEL  " } }, 0x38 }, "Print?Console1" },
{ { { { "KERNEL  " } }, 0x39 }, "Print?Console2" },
{ { { { "MAINLIB " } }, 0x2 }, "WaitMouseRelease" },
{ { { { "MAINLIB " } }, 0x3 }, "Sound" },
{ { { { "MAINLIB " } }, 0x5 }, "RedScreenOfDeath" },
{ { { { "MAINLIB " } }, 0x6 }, "PaletteColor" },
{ { { { "MAINLIB " } }, 0x7 }, "LAnd" },
{ { { { "MAINLIB " } }, 0x8 }, "Sign" },
{ { { { "MAINLIB " } }, 0xa }, "ClampRange" },
{ { { { "MAINLIB " } }, 0xb }, "PseudoRandom" },
{ { { { "MAINLIB " } }, 0xc }, "RandomRange" },
{ { { { "MAINLIB " } }, 0xd }, "Thousands" },
{ { { { "MAINLIB " } }, 0xe }, "GT32" },
{ { { { "MAINLIB " } }, 0xf }, "??32" },
{ { { { "MAINLIB " } }, 0x10 }, "??32" },
{ { { { "MAINLIB " } }, 0x11 }, "GetScore" },
{ { { { "MAINLIB " } }, 0x12 }, "SumData" },
{ { { { "MAINLIB " } }, 0x13 }, "SumAndDeobfuscate" },
{ { { { "MAINLIB " } }, 0x14 }, "ObfuscateAndSum" },
{ { { { "MAINLIB " } }, 0x15 }, "FormatNumber" },
{ { { { "MAINLIB " } }, 0x17 }, "PrintNewLine" },
{ { { { "MAINLIB " } }, 0x19 }, "SetTextPos" },
{ { { { "MAINLIB " } }, 0x1b }, "PrintStr" },
{ { { { "MAINLIB " } }, 0x1c }, "PrintLn" },
{ { { { "MAINLIB " } }, 0x1d }, "PrintNumber1" },
{ { { { "MAINLIB " } }, 0x1e }, "PrintNumber2" },
{ { { { "MAINLIB " } }, 0x1f }, "FormatMoney" },
{ { { { "MAINLIB " } }, 0x20 }, "PrintMoney" },
{ { { { "MAINLIB " } }, 0x21 }, "FontRenderConfig" },
{ { { { "MAINLIB " } }, 0x24 }, "DrawTime" },
{ { { { "MAINLIB " } }, 0x2c }, "WaitEvent" },
{ { { { "MAINLIB " } }, 0x2d }, "ConditionalWait" },
{ { { { "MAINLIB " } }, 0x2e }, "ConditionalSignal" },
{ { { { "MAINLIB " } }, 0x32 }, "PaletteChange" },
{ { { { "MAINLIB " } }, 0x33 }, "Nop" },
{ { { { "MAINLIB " } }, 0x34 }, "PossiblySetEvilState" },
{ { { { "MAINLIB " } }, 0x37 }, "FillLayoutRectangle" },
{ { { { "MAINLIB " } }, 0x38 }, "DrawColoredRectangle" },
{ { { { "MAINLIB " } }, 0x3d }, "PrintLnHelper" },
{ { { { "MAINLIB " } }, 0x44 }, "ErrorMessage" },
{ { { { "MAINLIB " } }, 0x45 }, "CheckDiskResult" },
{ { { { "MAINLIB " } }, 0x46 }, "CheckCorrectDisk" },
{ { { { "MAINLIB " } }, 0x47 }, "AskForDisk" },
{ { { { "MAINLIB " } }, 0x49 }, "DiskIO" },
{ { { { "MAINLIB " } }, 0x4a }, "WeirdDiskCheck" },
{ { { { "MAINLIB " } }, 0x4b }, "LoadImageBase" },
{ { { { "MAINLIB " } }, 0x4c }, "LoadImageInner" },
{ { { { "MAINLIB " } }, 0x4d }, "LoadImageOuter" },
{ { { { "MAINLIB " } }, 0x4e }, "TextPrintHelper" },
{ { { { "MAINLIB " } }, 0x4f }, "FormatPaddedNumber" },
{ { { { "MAINLIB " } }, 0x50 }, "TimeDigit" },
{ { { { "MAINLIB " } }, 0x51 }, "Sign32" },
{ { { { "MAINLIB " } }, 0x52 }, "?" },
{ { { { "MAINLIB " } }, 0x54 }, "PossiblyRunDiskCheck" },
{ { { { "OSUTIL  " } }, 0x3 }, "IntToStr" },
{ { { { "OSUTIL  " } }, 0x4 }, "Int2ToStr" },
{ { { { "OSUTIL  " } }, 0x5 }, "GotIntStr" },
{ { { { "OSUTIL  " } }, 0x6 }, "Upcase" },
{ { { { "PASCALIO" } }, 0x2 }, "j_get" },
{ { { { "PASCALIO" } }, 0x3 }, "f_get" },
{ { { { "PASCALIO" } }, 0x4 }, "f_put" },
{ { { { "PASCALIO" } }, 0x5 }, "f_eof" },
{ { { { "PASCALIO" } }, 0x6 }, "f_eoln" },
{ { { { "PASCALIO" } }, 0x7 }, "f_readint" },
{ { { { "PASCALIO" } }, 0x8 }, "f_writeint" },
{ { { { "PASCALIO" } }, 0x9 }, "f_readchar" },
{ { { { "PASCALIO" } }, 0xa }, "f_readstring" },
{ { { { "PASCALIO" } }, 0xb }, "f_writestring" },
{ { { { "PASCALIO" } }, 0xc }, "f_writebytes" },
{ { { { "PASCALIO" } }, 0xd }, "f_readln" },
{ { { { "PASCALIO" } }, 0xe }, "f_writeln" },
{ { { { "PASCALIO" } }, 0xf }, "FWriteChar" },
{ { { { "PASCALIO" } }, 0x10 }, "FPage" },
{ { { { "PASCALIO" } }, 0x11 }, "RdInt2" },
{ { { { "PASCALIO" } }, 0x12 }, "WrInt2" },
{ { { { "PASCALIO" } }, 0x13 }, "ReadBytes" },
{ { { { "PASCALIO" } }, 0x14 }, "WriteBytes" },
{ { { { "PASCALIO" } }, 0x15 }, "ReadTextChar" },
{ { { { "PERMHEAP" } }, 0x3 }, "permdispose" },
{ { { { "PERMHEAP" } }, 0x4 }, "permrelease" },
{ { { { "PERMHEAP" } }, 0x5 }, "permnew" },
{ { { { "SHIPLIB " } }, 0x2 }, "DoUserMenu" },
{ { { { "SHIPLIB " } }, 0x5 }, "DoRepair" },
{ { { { "SHIPLIB " } }, 0xf }, "RedFlashToggle" },
{ { { { "SHIPLIB " } }, 0x10 }, "SetClipAndWriteMode" },
{ { { { "SHIPLIB " } }, 0x16 }, "DrawStars" },
{ { { { "SHIPLIB " } }, 0x17 }, "RandomizeStars" },
{ { { { "SHIPLIB " } }, 0x18 }, "HandleBogeys" },
{ { { { "SHIPLIB " } }, 0x19 }, "FireWeaponAnimation" },
{ { { { "SHIPLIB " } }, 0x1a }, "WarpAnimation" },
{ { { { "SHIPLIB " } }, 0x1b }, "SetFillColor" },
{ { { { "SHIPLIB " } }, 0x1c }, "FillRectangle" },
{ { { { "STRINGOP" } }, 0x2 }, "concat" },
{ { { { "STRINGOP" } }, 0x3 }, "insert" },
{ { { { "STRINGOP" } }, 0x4 }, "copy" },
{ { { { "STRINGOP" } }, 0x5 }, "delete" },
{ { { { "STRINGOP" } }, 0x6 }, "pos" },
{ { { { "SUNDOG  " } }, 0x1 }, "Main" },
{ { { { "SUNDOG  " } }, 0x2 }, "BackgroundTask" },
{ { { { "SUNDOG  " } }, 0x4 }, "MainDispatch" },
{ { { { "USERPROG" } }, 0x1 }, "SystemStart" },
{ { { { "USERPROG" } }, 0x4 }, "FatalError" },
{ { { { "USERPROG" } }, 0x6 }, "VolSearch" },
{ { { { "USERPROG" } }, 0xa }, "LoadSystemPascal" },
{ { { { "USERPROG" } }, 0x1b }, "ReadSystemMiscInfo" },
{ { { { "USERPROG" } }, 0x1c }, "DetermineSystemParameters" },
{ { { { "USERPROG" } }, 0x1f }, "InitIO" },
{ { { { "USERPROG" } }, 0x21 }, "StartFaultHandler" },
{ { { { "USERPROG" } }, 0x28 }, "CupsCheck" },
{ { { { "WINDOWLI" } }, 0x5 }, "MouseDown" },
{ { { { "WINDOWLI" } }, 0x7 }, "ShowItemName" },
{ { { { "WINDOWLI" } }, 0xf }, "DrawButtons" },
{ { { { "WINDOWLI" } }, 0x10 }, "MouseClick" },
{ { { { "WINDOWLI" } }, 0x13 }, "SetButtonLayout" },
{ { { { "WINDOWLI" } }, 0x14 }, "SetButtonText" },
{ { { { "WINDOWLI" } }, 0x15 }, "DrawWindow" },
{ { { { "WINDOWLI" } }, 0x17 }, "DrugEffects" },
{ { { { "WINDOWLI" } }, 0x19 }, "DrawButton" },
{ { { { "XDOFIGHT" } }, 0x1 }, "XDoFight" },
{ { { { "XDOFIGHT" } }, 0x5 }, "TargetDestroyed" },
{ { { { "XDOFIGHT" } }, 0x6 }, "FireWeapon" },
{ { { { "XDOFIGHT" } }, 0xb }, "MouseToShipMovement" },
{ { { { "XDOFIGHT" } }, 0xc }, "DoShooting" },
{ { { { "XDOFIGHT" } }, 0x10 }, "TacticalMenu" },
{ { { { "XDOFIGHT" } }, 0x13 }, "TractorBeam" },
{ { { { "XDOINTER" } }, 0x1 }, "XDoInteraction" },
{ { { { "XDOINTER" } }, 0xa }, "GetStringOffset" },
{ { { { "XDOINTER" } }, 0xb }, "LookupString" },
{ { { { "XDOINTER" } }, 0xc }, "SeekStringAlt" },
{ { { { "XDOINTER" } }, 0xd }, "MapCase" },
{ { { { "XDOINTER" } }, 0xe }, "GetNextByte" },
{ { { { "XDOINTER" } }, 0x10 }, "OuterIndirectOut" },
{ { { { "XDOINTER" } }, 0x11 }, "StringCharOut" },
{ { { { "XDOINTER" } }, 0x13 }, "HandleChar" },
{ { { { "XDOINTER" } }, 0x14 }, "StringIndirectOut2" },
{ { { { "XDOINTER" } }, 0x16 }, "StartInteraction" },
{ { { { "XDOINTER" } }, 0x1d }, "ComputeStringOffsets" },
{ { { { "XDOINTER" } }, 0x1f }, "LoadDialogBlocks" },
{ { { { "XDOINTER" } }, 0x22 }, "WeirdLoadSector" },
{ { { { "XDOINTER" } }, 0x24 }, "InitDialogs" },
{ { { { "XDOREPAI" } }, 0x1 }, "XDoRepair" },
{ { { { "XDOREPAI" } }, 0x5 }, "Cargo" },
{ { { { "XDOREPAI" } }, 0x7 }, "DragItem" },
{ { { { "XDOUSERM" } }, 0x1 }, "XDoUserMenu" },
{ { { { "XDOUSERM" } }, 0x3 }, "ShowStats" },
{ { { { "XDOUSERM" } }, 0x6 }, "WaitEvent" },
{ { { { "XDOUSERM" } }, 0x7 }, "ShowCondition" },
{ { { { "XDOUSERM" } }, 0xb }, "ShowTime" },
{ { { { "XDOUSERM" } }, 0xc }, "ShowMoney" },
{ { { { "XDOUSERM" } }, 0xd }, "ShowAttributes" },
{ { { { "XDOUSERM" } }, 0xe }, "ShowLocation" },
{ { { { "XMOVEINB" } }, 0x1 }, "XMoveInBuilding" },
{ { { { "XMOVEINB" } }, 0x1a }, "SlotMachine" },
{ { { { "XMOVEONS" } }, 0x1 }, "XMoveOnShip" },
{ { { { "XPILOTAG" } }, 0x1 }, "XPilotage" },
{ { { { "XPILOTAG" } }, 0x4 }, "WaitUserAction" },
{ { { { "XPILOTAG" } }, 0x6 }, "NavigationMenuSetup" },
{ { { { "XPILOTAG" } }, 0x7 }, "NavigationMenu" },
{ { { { "XPILOTAG" } }, 0xa }, "MainMenuSetup" },
{ { { { "XSTARTUP" } }, 0x1 }, "XStartup" },
{ { { { "XSTARTUP" } }, 0x2 }, "InitPalette" },
{ { { { "XSTARTUP" } }, 0x3 }, "InitGFX" },
{ { { { "XSTARTUP" } }, 0x4 }, "InitVDIBuffer" },
{ { { { "XSTARTUP" } }, 0x5 }, "AllocVDIBuffer" },
{ { { { "XSTARTUP" } }, 0xa }, "LoadData" },
{ { { { "XSTARTUP" } }, 0xf }, "LoadResources" },
{ { { { "XSTARTUP" } }, 0x11 }, "ShowSavedGameStatus" },
{ { { { "XSTARTUP" } }, 0x14 }, "StartupMenu" },
{ { { { "XSTARTUP" } }, 0x15 }, "Librarian" },
{ { { { "XSTARTUP" } }, 0x36 }, "AttributeSetting" },
{ { { { "XSTARTUP" } }, 0x46 }, "IntroText" },
{ { { { "XSTARTUP" } }, 0x49 }, "PlayerDied" },
    // clang-format on
